apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-fmcg
    orgId: 1
    isDefault: true
    editable: true
    jsonData:
      server: clickhouse
      port: 9000
      protocol: native
      username: default
      defaultDatabase: default
      dialTimeout: 10
      queryTimeout: 60
    secureJsonData:
      password: ""

  - name: Prometheus
    type: prometheus
    uid: prometheus-fmcg
    orgId: 1
    url: http://prometheus:9090
    editable: true
    jsonData:
      timeInterval: 15s
