apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-fmcg
    orgId: 1
    isDefault: true
    editable: true
    jsonData:
      server: clickhouse
      port: 9000
      protocol: native
      username: default
      defaultDatabase: default
      dialTimeout: 10
      queryTimeout: 60
    secureJsonData:
      password: ""

  - name: Prometheus
    type: prometheus
    uid: prometheus-fmcg
    orgId: 1
    url: http://prometheus:9090
    editable: true
    jsonData:
      timeInterval: 15s

  - name: CubeJS
    type: postgres
    uid: cubejs-fmcg
    orgId: 1
    url: cubejs:15432
    user: admin
    secureJsonData:
      password: fmcg_cubejs_secret_key_123
    jsonData:
      database: db
      sslmode: disable
      encrypt: false
